apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: x2vbwdu3s-nodejs-gitops
  description: This is GitOps manifest for x2vbwdu3s-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=x2vbwdu3s-nodejs
    backstage.io/kubernetes-id: x2vbwdu3s-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: x2vbwdu3s-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:x2vbwdu3s-nodejs
