apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x2vbwdu3s-nodejs
  janus-idp.io/tekton: x2vbwdu3s-nodejs
  backstage.io/kubernetes-id: x2vbwdu3s-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x2vbwdu3s-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
